### ISSUE TITLE
Problem keyboat

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubports-touch#100]
I have a little problem with the keyboard when I come back on a word, the previous word comes so glued I am obliged to erase it.
Do you have the same problem?

**Comment by bastos77** [comment]
I have the same issue on my FP2. But I think, this is already in discussion

**Comment by Flohack74** [comment]
Good Morning,

we have an extra bugtracker for each core App and system component, so also for the keyboard: https://github.com/ubports/keyboard-component/issues. Please use that project rather than this one, as it is for sure not device-dependent. Also look at https://github.com/ubports/keyboard-component/issues?q=is%3Aissue+is%3Aclosed where there are closed bugs, they are in devel or rc images, but maybe not in stable now.
