### ISSUE TITLE
About UBports under System indicator

### ISSUE THREAD

**Issue by Jujuyeh** [ubports/ubports-touch#108]
I recommend adding a link to the UBports app under System indicator. Maybe also in System Settings under "About this device".

**Comment by ChloeWolfieGirl** [comment]
I dont think this should be in an indicator.

Perhaps when youre going through set up of a new device, it asks you if you want to install the ubports help application? Just have it as a tick box with default off, I dont know what screen it should be on though, something to discuss?

**Comment by doniks** [comment]
To me https://github.com/ubports/ubports-touch/issues/108 and https://github.com/ubports/ubports-touch/issues/175 sound very related. What about: Replace the "Ubuntu help ..." button with "Ubports help ..." and make it launch the app?

As for ChloeWolfieGirls suggestion of a tick box when setting up - I would strongly advice against from a user experience perspective. I always vote for a good default rather than a decision (check box) being forced on me. A user installing ubports will typically not care about preinstalling ubports app. That would be the last thing on my mind. I want to get this thing up. Then I want to be able to communicate with my friends, look at funny cat videos, or see what the fuzz is about convergence.

**Comment by ChloeWolfieGirl** [comment]
I suggest this because Id rather have a 1 time button, then something thats constantly there.

Though I get the complaint, anyone whos ever used a modern non-stock android phone knows the pain.

**Comment by NeoTheThird** [comment]
I have no idea if it works, but this ubports/indicator-session#1 should add a link to the bug tracker.

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/indicator-session/commit/334566cca2a604e6d853fb1720ae45a92e31c613
