### ISSUE TITLE
Aethercast bq e4.5

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#132]
Will it have aethercast in this device?

**Comment by lduboeuf** [comment]
i've heard somewhere on ubuntu touch forums that BQ 4.5 is not powerfull enough to make it work properly. i'm afraid that it will not be possible.

**Comment by fmulcar** [comment]
Let's see,when I was installed android,the phone run without problems applications with miracast.?
Canonical will never have to worry about upgrade libhybris.?
Now we're going to do the same to us??

**Comment by UniversalSuperBox** [comment]
If the Canonical image did not support Miracast, it is unlikely at best that we will support it.

As for upgrading the Android layer, that is impossible for us since the Android source tree for this device is closed-source. If you would like to discuss this, please open a thread on [our forum[(https://forums.ubports.com).
