### ISSUE TITLE
Vivid rootfs for Halium

### ISSUE THREAD

**Issue by doniks** [ubports/ubports-touch#207]
It would be nice to have a Halium rootfs for the existing/current/old Ubuntu Touch system.

Especially since it seems that the future/new Xenial based system appears to still be a ways away.

I just tried with vivid-preinstalled-touch-armhf.tar.gz from
http://cdimage.ubuntu.com/ubuntu-touch/vivid/daily-preinstalled/current/
but it seems that init fails after the switch_root followed by kernel panic and reboot.

**Comment by mariogrip** [comment]
We wont use Halium for vivid, fist off since vivid is upstart based and halium and xenial is systemd based. And also since we wont invest much more time with vivid other that bug fixes and user level changes and improvements. this is due to vivid is end of life and we want to use our development force to move forward to the next Ubuntu release.
