### ISSUE TITLE
Nexus 4

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#241]
- Device: Nexus 4
- Channel: Legacy
- Build: 26

## Steps to reproduce

1. Any solution for nexus 4 users?
Someone willing to help?
2. It's been 5 months and we have no sound or mobile data.
3. We have to wait another 5 months or more, to have a stable ota?
This is a serious development?
This happens when one agrees to make the port and realizes that he has no idea what he does.

**Comment by NeoTheThird** [comment]
I appreciate that there has been some delay here, but this expectant attitude is not cool towards people who are working *for free and without any financial reimbursement* next to their day-job. We will not tolerate this attitude.

To your question: On the last [Q&A](https://youtu.be/MGvo5sGEHmU) we announced that the Nexus 4 will be included in OTA 2, and we explained the reasons for the hold up. Due to all the [work at ubucon europe in paris](https://ubports.com/blog/ubports-blog-1/post/ubports-goes-ubucon-paris-71), we couldn't get around to push the nexus 4 to rc yet, it should be live any minute now.
